### ISSUE TITLE
flutterEurope ticket purchase -500 Error on payment result and no ticket

### ISSUE THREAD

**Issue by jameshp** [eventil/eventil.com#227]
Just tried to by a ticket with a VISA (without beeig loged in or registered on the eventil site), and got to the payment page. 
Received a 500 Error message, but also a confirmation from VISA that the amount was deducted from my account. 
Either send me the ticket or refund the amount. Thx. 
Message with more details already sent to hello@eventil.com

**Comment by annalaufey** [comment]
Did this ever get resolved for you? I also have trouble with my ticket and I can't get any assistance for it.

**Comment by jameshp** [comment]
yes, I was contacted and they later resolved it.  But I'm not sure if they
fixed the issue.

**Comment by rafpiek** [comment]
It's not resolved. I have similar problems. I've paid but didn't receive anything on my email.

**Comment by zaiste** [comment]
@rafpiek You made a typo mistake in the email you provided (in the TLD name). Could you confirm there was no `500` error on your side ?
